plugins {
    id 'com.android.application'
}

android {
    compileSdk 33

    defaultConfig {
        applicationId "poc.app"
        minSdk 29
        targetSdk 32
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    namespace 'poc.app'
}

dependencies {
    implementation 'com.github.ChickenHook:RestrictionBypass:2.2'
    implementation 'com.google.code.gson:gson:2.10.1'
}